#  Copyright 2026 Benjamin Callaghan

#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Build .NET

on:
  workflow_run:
    workflows: [Build Native]
    types: [completed]

jobs:
  build_and_test:
    name: test on ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15-intel
            rid: osx-x64
            artifact: macos-arm-lib
          - os: macos-15
            rid: osx-arm64
            artifact: macos-intel-lib
          - os: ubuntu-latest
            rid: linux-x64
            artifact: linux-lib
          - os: windows-2025
            rid: win-x64
            artifact: windows-bin

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Download native libraries
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: ${{ matrix.artifact }}
          path: artifacts/${{ matrix.rid }}

      - name: Test
        run: dotnet test --configuration Release --runtime ${{ matrix.rid }} --verbosity normal --filter Requires!=YubiHSM
        # The SDK is available for limited testing, but not a full device.

      - name: Pack
        run: dotnet pack --no-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: nuget-packages
          path: ./**/*.symbols.nupkg
