#  Copyright 2015-2018 Yubico AB

#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Build Native

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_linux:
    name: build on ubuntu:25.10 (clang)
    runs-on: ubuntu-latest
    container: ubuntu:25.10

    steps:
      - name: install dependencies from package management
        env:
          CC: clang
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -q -y build-essential \
                            cmake pkg-config \
                            gengetopt \
                            help2man \
                            libcurl4-openssl-dev \
                            libedit-dev \
                            libpcsclite-dev \
                            libusb-1.0-0-dev \
                            libssl-dev \
                            file \
                            curl \
                            jq \
                            zlib1g-dev
          apt install -q -y clang llvm lld
          apt install -q -y git

      - name: clone the yubihsm-shell repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: apply environment specific changes to CMakeLists.txt
        working-directory: yubihsm-shell
        run: |
          # ubuntu 24.10 and above comes with _FORTIFY_SOURCE already set
          sed -i 's/add_definitions (-D_FORTIFY_SOURCE=2)/add_definitions (-D_FORTIFY_SOURCE=3)/' cmake/SecurityFlags.cmake

      - name: do build
        working-directory: yubihsm-shell
        env:
          CC: clang
          VERBOSE: 1
        run: |
          mkdir build
          cd build
          cmake -DRELEASE_BUILD=1 -DWITHOUT_YKYH=1 \
            -DCMAKE_AR=/usr/bin/llvm-ar \
            -DCMAKE_RANLIB=/usr/bin/llvm-ranlib \
            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" \
            ..
          cmake --build .

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: linux-lib
          path: yubihsm-shell/build/lib

  build_macos:
    name: build on macos
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15-intel
            artifact: macos-intel-lib
          - os: macos-15
            artifact: macos-arm-lib

    steps:
      - name: install dependencies using brew
        run: brew install gengetopt help2man libedit opensc
        env:
          HOMEBREW_REQUIRE_TAP_TRUST: 1

      - name: clone the yubihsm-shell repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: do build
        working-directory: yubihsm-shell
        env:
          VERBOSE: 1
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: yubihsm-shell/build/lib

  source:
    name: Build dist with Linux
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          submodules: true
      
      - name: Install prerequisites
        run: |
          set -x
          sudo apt -q update
          sudo apt install libpcsclite-dev gengetopt help2man libedit-dev libcurl4-openssl-dev libssl-dev libusb-1.0-0-dev zlib1g-dev
      
      - name: Create tar.gz
        working-directory: yubihsm-shell
        run: |
          mkdir $GITHUB_WORKSPACE/artifact
          set -x
          ./resources/release/make_src_dist.sh
          mv yubihsm-shell-.tar.gz $GITHUB_WORKSPACE/artifact/
          cp -r resources/release $GITHUB_WORKSPACE/artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: yubihsm-shell-src
          path: artifact
  
  build_windows:
    name: Build on Windows
    needs: source
    runs-on: windows-2025
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download source from source job
        uses: actions/download-artifact@v8
        with: 
          name: yubihsm-shell-src

      - name: Extract source
        run: |
          Set-PSDebug -Trace 1
          tar xf yubihsm-shell-.tar.gz

      # The script make_release_binaries.ps1 depends on the buildtrees folder, which can't be cached.
      # - name: Restore VCPKG cache
      #   uses: LegalizeAdulthood/vcpkg-github-cache@v1
      #   with:
      #     token: ${{ github.token }}
      #     vcpkg-root: C:/vcpkg
      #     bootstrap: false

      - name: Build
        env:
          ARCH_CMAKE: x64
          ARCH: x64
        run: |
          Set-PSDebug -Trace 1
          cd $env:GITHUB_WORKSPACE/release/win
          ./make_release_binaries.ps1 $env:ARCH_CMAKE C:/vcpkg $env:GITHUB_WORKSPACE\yubihsm-shell-

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-bin
          path: release/win/yubihsm-shell-x64/bin/
